name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    paths-ignore: [.github/**]
  pull_request:
    branches:
    - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The name of the job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of the branch is ${{ github.ref }}"
      - uses: actions/checkout@v3.5.2
      - name: List files in the repository

  
  
      
